#!/bin/sh

echo "Running dotnet format..."
dotnet format --verify-no-changes
if [ $? -ne 0 ]; then
  echo "Code is not formatted. Run 'dotnet format' before committing."
  exit 1
fi

echo "Running dotnet test..."
dotnet test --no-build --verbosity minimal
if [ $? -ne 0 ]; then
  echo "Tests failed. Fix them before committing."
  exit 1
fi

echo "Generating documentation..."
make clean-docs
make docs

git add docs/_site

exit 0
