global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "dotnet-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:5000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgresql-exporter:9187"]
