### YamlMime:ManagedReference
items:
- uid: Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2
  commentId: T:Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2
  id: ICommandPipelineBehaviour`2
  parent: Project.Application.Configuration.Commands
  children:
  - Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle(`0,System.Func{`0,System.Threading.Tasks.Task{`1}},System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: ICommandPipelineBehaviour<TCommand, TResult>
  nameWithType: ICommandPipelineBehaviour<TCommand, TResult>
  fullName: Project.Application.Configuration.Commands.ICommandPipelineBehaviour<TCommand, TResult>
  type: Interface
  source:
    remote:
      path: src/Project.Application/Configuration/Commands/ICommandPipelineBehaviour.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: ICommandPipelineBehaviour
    path: ../src/Project.Application/Configuration/Commands/ICommandPipelineBehaviour.cs
    startLine: 2
  assemblies:
  - Project.Application
  namespace: Project.Application.Configuration.Commands
  syntax:
    content: 'public interface ICommandPipelineBehaviour<TCommand, TResult> where TCommand : ICommand<TResult>'
    typeParameters:
    - id: TCommand
    - id: TResult
    content.vb: Public Interface ICommandPipelineBehaviour(Of TCommand As ICommand(Of TResult), TResult)
  nameWithType.vb: ICommandPipelineBehaviour(Of TCommand, TResult)
  fullName.vb: Project.Application.Configuration.Commands.ICommandPipelineBehaviour(Of TCommand, TResult)
  name.vb: ICommandPipelineBehaviour(Of TCommand, TResult)
- uid: Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle(`0,System.Func{`0,System.Threading.Tasks.Task{`1}},System.Threading.CancellationToken)
  commentId: M:Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle(`0,System.Func{`0,System.Threading.Tasks.Task{`1}},System.Threading.CancellationToken)
  id: Handle(`0,System.Func{`0,System.Threading.Tasks.Task{`1}},System.Threading.CancellationToken)
  parent: Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2
  langs:
  - csharp
  - vb
  name: Handle(TCommand, Func<TCommand, Task<TResult>>, CancellationToken)
  nameWithType: ICommandPipelineBehaviour<TCommand, TResult>.Handle(TCommand, Func<TCommand, Task<TResult>>, CancellationToken)
  fullName: Project.Application.Configuration.Commands.ICommandPipelineBehaviour<TCommand, TResult>.Handle(TCommand, System.Func<TCommand, System.Threading.Tasks.Task<TResult>>, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/Project.Application/Configuration/Commands/ICommandPipelineBehaviour.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Handle
    path: ../src/Project.Application/Configuration/Commands/ICommandPipelineBehaviour.cs
    startLine: 5
  assemblies:
  - Project.Application
  namespace: Project.Application.Configuration.Commands
  syntax:
    content: Task<TResult> Handle(TCommand command, Func<TCommand, Task<TResult>> next, CancellationToken cancellationToken)
    parameters:
    - id: command
      type: '{TCommand}'
    - id: next
      type: System.Func{{TCommand},System.Threading.Tasks.Task{{TResult}}}
    - id: cancellationToken
      type: System.Threading.CancellationToken
    return:
      type: System.Threading.Tasks.Task{{TResult}}
    content.vb: Function Handle(command As TCommand, [next] As Func(Of TCommand, Task(Of TResult)), cancellationToken As CancellationToken) As Task(Of TResult)
  overload: Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle*
  nameWithType.vb: ICommandPipelineBehaviour(Of TCommand, TResult).Handle(TCommand, Func(Of TCommand, Task(Of TResult)), CancellationToken)
  fullName.vb: Project.Application.Configuration.Commands.ICommandPipelineBehaviour(Of TCommand, TResult).Handle(TCommand, System.Func(Of TCommand, System.Threading.Tasks.Task(Of TResult)), System.Threading.CancellationToken)
  name.vb: Handle(TCommand, Func(Of TCommand, Task(Of TResult)), CancellationToken)
references:
- uid: Project.Application.Configuration.Commands
  commentId: N:Project.Application.Configuration.Commands
  href: Project.html
  name: Project.Application.Configuration.Commands
  nameWithType: Project.Application.Configuration.Commands
  fullName: Project.Application.Configuration.Commands
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Configuration
    name: Configuration
    href: Project.Application.Configuration.html
  - name: .
  - uid: Project.Application.Configuration.Commands
    name: Commands
    href: Project.Application.Configuration.Commands.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Configuration
    name: Configuration
    href: Project.Application.Configuration.html
  - name: .
  - uid: Project.Application.Configuration.Commands
    name: Commands
    href: Project.Application.Configuration.Commands.html
- uid: Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle*
  commentId: Overload:Project.Application.Configuration.Commands.ICommandPipelineBehaviour`2.Handle
  href: Project.Application.Configuration.Commands.ICommandPipelineBehaviour-2.html#Project_Application_Configuration_Commands_ICommandPipelineBehaviour_2_Handle__0_System_Func__0_System_Threading_Tasks_Task__1___System_Threading_CancellationToken_
  name: Handle
  nameWithType: ICommandPipelineBehaviour<TCommand, TResult>.Handle
  fullName: Project.Application.Configuration.Commands.ICommandPipelineBehaviour<TCommand, TResult>.Handle
  nameWithType.vb: ICommandPipelineBehaviour(Of TCommand, TResult).Handle
  fullName.vb: Project.Application.Configuration.Commands.ICommandPipelineBehaviour(Of TCommand, TResult).Handle
- uid: '{TCommand}'
  commentId: '!:TCommand'
  definition: TCommand
  name: TCommand
  nameWithType: TCommand
  fullName: TCommand
- uid: System.Func{{TCommand},System.Threading.Tasks.Task{{TResult}}}
  commentId: T:System.Func{`0,System.Threading.Tasks.Task{`1}}
  parent: System
  definition: System.Func`2
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<TCommand, Task<TResult>>
  nameWithType: Func<TCommand, Task<TResult>>
  fullName: System.Func<TCommand, System.Threading.Tasks.Task<TResult>>
  nameWithType.vb: Func(Of TCommand, Task(Of TResult))
  fullName.vb: System.Func(Of TCommand, System.Threading.Tasks.Task(Of TResult))
  name.vb: Func(Of TCommand, Task(Of TResult))
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: TCommand
  - name: ','
  - name: " "
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: ','
  - name: " "
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
  - name: )
- uid: System.Threading.CancellationToken
  commentId: T:System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{{TResult}}
  commentId: T:System.Threading.Tasks.Task{`1}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: TCommand
  name: TCommand
  nameWithType: TCommand
  fullName: TCommand
- uid: System.Func`2
  commentId: T:System.Func`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<T, TResult>
  nameWithType: Func<T, TResult>
  fullName: System.Func<T, TResult>
  nameWithType.vb: Func(Of T, TResult)
  fullName.vb: System.Func(Of T, TResult)
  name.vb: Func(Of T, TResult)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading
  commentId: N:System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading
  nameWithType: System.Threading
  fullName: System.Threading
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
