### YamlMime:ManagedReference
items:
- uid: Project.Application.Configuration.IExecutionContextAccessor
  commentId: T:Project.Application.Configuration.IExecutionContextAccessor
  id: IExecutionContextAccessor
  parent: Project.Application.Configuration
  children:
  - Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
  - Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
  langs:
  - csharp
  - vb
  name: IExecutionContextAccessor
  nameWithType: IExecutionContextAccessor
  fullName: Project.Application.Configuration.IExecutionContextAccessor
  type: Interface
  source:
    remote:
      path: src/Project.Application/Configuration/IExecutionContextAcessor.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: IExecutionContextAccessor
    path: ../src/Project.Application/Configuration/IExecutionContextAcessor.cs
    startLine: 2
  assemblies:
  - Project.Application
  namespace: Project.Application.Configuration
  syntax:
    content: public interface IExecutionContextAccessor
    content.vb: Public Interface IExecutionContextAccessor
- uid: Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
  commentId: P:Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
  id: CorrelationId
  parent: Project.Application.Configuration.IExecutionContextAccessor
  langs:
  - csharp
  - vb
  name: CorrelationId
  nameWithType: IExecutionContextAccessor.CorrelationId
  fullName: Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
  type: Property
  source:
    remote:
      path: src/Project.Application/Configuration/IExecutionContextAcessor.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: CorrelationId
    path: ../src/Project.Application/Configuration/IExecutionContextAcessor.cs
    startLine: 4
  assemblies:
  - Project.Application
  namespace: Project.Application.Configuration
  syntax:
    content: Guid CorrelationId { get; }
    parameters: []
    return:
      type: System.Guid
    content.vb: ReadOnly Property CorrelationId As Guid
  overload: Project.Application.Configuration.IExecutionContextAccessor.CorrelationId*
- uid: Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
  commentId: P:Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
  id: IsAvailable
  parent: Project.Application.Configuration.IExecutionContextAccessor
  langs:
  - csharp
  - vb
  name: IsAvailable
  nameWithType: IExecutionContextAccessor.IsAvailable
  fullName: Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
  type: Property
  source:
    remote:
      path: src/Project.Application/Configuration/IExecutionContextAcessor.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: IsAvailable
    path: ../src/Project.Application/Configuration/IExecutionContextAcessor.cs
    startLine: 5
  assemblies:
  - Project.Application
  namespace: Project.Application.Configuration
  syntax:
    content: bool IsAvailable { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsAvailable As Boolean
  overload: Project.Application.Configuration.IExecutionContextAccessor.IsAvailable*
references:
- uid: Project.Application.Configuration
  commentId: N:Project.Application.Configuration
  href: Project.html
  name: Project.Application.Configuration
  nameWithType: Project.Application.Configuration
  fullName: Project.Application.Configuration
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Configuration
    name: Configuration
    href: Project.Application.Configuration.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Configuration
    name: Configuration
    href: Project.Application.Configuration.html
- uid: Project.Application.Configuration.IExecutionContextAccessor.CorrelationId*
  commentId: Overload:Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
  href: Project.Application.Configuration.IExecutionContextAccessor.html#Project_Application_Configuration_IExecutionContextAccessor_CorrelationId
  name: CorrelationId
  nameWithType: IExecutionContextAccessor.CorrelationId
  fullName: Project.Application.Configuration.IExecutionContextAccessor.CorrelationId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Project.Application.Configuration.IExecutionContextAccessor.IsAvailable*
  commentId: Overload:Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
  href: Project.Application.Configuration.IExecutionContextAccessor.html#Project_Application_Configuration_IExecutionContextAccessor_IsAvailable
  name: IsAvailable
  nameWithType: IExecutionContextAccessor.IsAvailable
  fullName: Project.Application.Configuration.IExecutionContextAccessor.IsAvailable
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
