### YamlMime:ManagedReference
items:
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  commentId: T:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  id: UserDetailsDTO
  parent: Project.Application.Users.Queries.GetUserDetails
  children:
  - Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
  - Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
  - Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
  langs:
  - csharp
  - vb
  name: UserDetailsDTO
  nameWithType: UserDetailsDTO
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  type: Class
  source:
    remote:
      path: src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: UserDetailsDTO
    path: ../src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
    startLine: 2
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Queries.GetUserDetails
  syntax:
    content: public class UserDetailsDTO
    content.vb: Public Class UserDetailsDTO
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
  commentId: P:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
  id: FirstName
  parent: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  langs:
  - csharp
  - vb
  name: FirstName
  nameWithType: UserDetailsDTO.FirstName
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
  type: Property
  source:
    remote:
      path: src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: FirstName
    path: ../src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
    startLine: 4
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Queries.GetUserDetails
  syntax:
    content: public required string FirstName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FirstName As String
  overload: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName*
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
  commentId: P:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
  id: LastName
  parent: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  langs:
  - csharp
  - vb
  name: LastName
  nameWithType: UserDetailsDTO.LastName
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
  type: Property
  source:
    remote:
      path: src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: LastName
    path: ../src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
    startLine: 5
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Queries.GetUserDetails
  syntax:
    content: public required string LastName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LastName As String
  overload: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName*
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
  commentId: P:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
  id: Email
  parent: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: UserDetailsDTO.Email
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
  type: Property
  source:
    remote:
      path: src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Email
    path: ../src/Project.Application/Users/Queries/GetUserDetails/UserDetailsDTO.CS
    startLine: 6
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Queries.GetUserDetails
  syntax:
    content: public required string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email*
references:
- uid: Project.Application.Users.Queries.GetUserDetails
  commentId: N:Project.Application.Users.Queries.GetUserDetails
  href: Project.html
  name: Project.Application.Users.Queries.GetUserDetails
  nameWithType: Project.Application.Users.Queries.GetUserDetails
  fullName: Project.Application.Users.Queries.GetUserDetails
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Queries
    name: Queries
    href: Project.Application.Users.Queries.html
  - name: .
  - uid: Project.Application.Users.Queries.GetUserDetails
    name: GetUserDetails
    href: Project.Application.Users.Queries.GetUserDetails.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Queries
    name: Queries
    href: Project.Application.Users.Queries.html
  - name: .
  - uid: Project.Application.Users.Queries.GetUserDetails
    name: GetUserDetails
    href: Project.Application.Users.Queries.GetUserDetails.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName*
  commentId: Overload:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
  href: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.html#Project_Application_Users_Queries_GetUserDetails_UserDetailsDTO_FirstName
  name: FirstName
  nameWithType: UserDetailsDTO.FirstName
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.FirstName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName*
  commentId: Overload:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
  href: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.html#Project_Application_Users_Queries_GetUserDetails_UserDetailsDTO_LastName
  name: LastName
  nameWithType: UserDetailsDTO.LastName
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.LastName
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email*
  commentId: Overload:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
  href: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.html#Project_Application_Users_Queries_GetUserDetails_UserDetailsDTO_Email
  name: Email
  nameWithType: UserDetailsDTO.Email
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.Email
