### YamlMime:ManagedReference
items:
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests
  commentId: T:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests
  id: DomainNotificationBaseTests
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  children:
  - Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId
  - Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
  langs:
  - csharp
  - vb
  name: DomainNotificationBaseTests
  nameWithType: DomainNotificationBaseTests
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests
  type: Class
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: DomainNotificationBaseTests
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
    startLine: 5
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  syntax:
    content: public class DomainNotificationBaseTests
    content.vb: Public Class DomainNotificationBaseTests
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
  commentId: M:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
  id: Constructor_ShouldSetDomainEvent
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests
  langs:
  - csharp
  - vb
  name: Constructor_ShouldSetDomainEvent()
  nameWithType: DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent()
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent()
  type: Method
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Constructor_ShouldSetDomainEvent
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
    startLine: 7
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  syntax:
    content: >-
      [Fact]

      public void Constructor_ShouldSetDomainEvent()
    content.vb: >-
      <Fact>

      Public Sub Constructor_ShouldSetDomainEvent()
  overload: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent*
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId
  commentId: M:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId
  id: Constructor_ShouldGenerateId
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests
  langs:
  - csharp
  - vb
  name: Constructor_ShouldGenerateId()
  nameWithType: DomainNotificationBaseTests.Constructor_ShouldGenerateId()
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId()
  type: Method
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Constructor_ShouldGenerateId
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/DomainEvents/DomainNotificationBaseTests.cs
    startLine: 20
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  syntax:
    content: >-
      [Fact]

      public void Constructor_ShouldGenerateId()
    content.vb: >-
      <Fact>

      Public Sub Constructor_ShouldGenerateId()
  overload: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId*
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
references:
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  commentId: N:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  href: Project.html
  name: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  nameWithType: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Tests
    name: Tests
    href: Project.Tests.html
  - name: .
  - uid: Project.Tests.UnitTests
    name: UnitTests
    href: Project.Tests.UnitTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application
    name: Application
    href: Project.Tests.UnitTests.Application.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests
    name: ConfigurationTests
    href: Project.Tests.UnitTests.Application.ConfigurationTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
    name: DomainEvents
    href: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Tests
    name: Tests
    href: Project.Tests.html
  - name: .
  - uid: Project.Tests.UnitTests
    name: UnitTests
    href: Project.Tests.UnitTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application
    name: Application
    href: Project.Tests.UnitTests.Application.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests
    name: ConfigurationTests
    href: Project.Tests.UnitTests.Application.ConfigurationTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents
    name: DomainEvents
    href: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent*
  commentId: Overload:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
  href: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.html#Project_Tests_UnitTests_Application_ConfigurationTests_DomainEvents_DomainNotificationBaseTests_Constructor_ShouldSetDomainEvent
  name: Constructor_ShouldSetDomainEvent
  nameWithType: DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldSetDomainEvent
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId*
  commentId: Overload:Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId
  href: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.html#Project_Tests_UnitTests_Application_ConfigurationTests_DomainEvents_DomainNotificationBaseTests_Constructor_ShouldGenerateId
  name: Constructor_ShouldGenerateId
  nameWithType: DomainNotificationBaseTests.Constructor_ShouldGenerateId
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.DomainEvents.DomainNotificationBaseTests.Constructor_ShouldGenerateId
