### YamlMime:ManagedReference
items:
- uid: Project.Application.Users.Mappers.UserMapper
  commentId: T:Project.Application.Users.Mappers.UserMapper
  id: UserMapper
  parent: Project.Application.Users.Mappers
  children:
  - Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO(Project.Domain.Users.User)
  langs:
  - csharp
  - vb
  name: UserMapper
  nameWithType: UserMapper
  fullName: Project.Application.Users.Mappers.UserMapper
  type: Class
  source:
    remote:
      path: src/Project.Application/Users/Mappers/UserMapper.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: UserMapper
    path: ../src/Project.Application/Users/Mappers/UserMapper.cs
    startLine: 5
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Mappers
  syntax:
    content: public static class UserMapper
    content.vb: Public Module UserMapper
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO(Project.Domain.Users.User)
  commentId: M:Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO(Project.Domain.Users.User)
  id: ToUserDetailsDTO(Project.Domain.Users.User)
  isExtensionMethod: true
  parent: Project.Application.Users.Mappers.UserMapper
  langs:
  - csharp
  - vb
  name: ToUserDetailsDTO(User)
  nameWithType: UserMapper.ToUserDetailsDTO(User)
  fullName: Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO(Project.Domain.Users.User)
  type: Method
  source:
    remote:
      path: src/Project.Application/Users/Mappers/UserMapper.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: ToUserDetailsDTO
    path: ../src/Project.Application/Users/Mappers/UserMapper.cs
    startLine: 7
  assemblies:
  - Project.Application
  namespace: Project.Application.Users.Mappers
  syntax:
    content: public static UserDetailsDTO ToUserDetailsDTO(this User user)
    parameters:
    - id: user
      type: Project.Domain.Users.User
    return:
      type: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
    content.vb: Public Shared Function ToUserDetailsDTO(user As User) As UserDetailsDTO
  overload: Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO*
references:
- uid: Project.Application.Users.Mappers
  commentId: N:Project.Application.Users.Mappers
  href: Project.html
  name: Project.Application.Users.Mappers
  nameWithType: Project.Application.Users.Mappers
  fullName: Project.Application.Users.Mappers
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Mappers
    name: Mappers
    href: Project.Application.Users.Mappers.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Mappers
    name: Mappers
    href: Project.Application.Users.Mappers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO*
  commentId: Overload:Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO
  href: Project.Application.Users.Mappers.UserMapper.html#Project_Application_Users_Mappers_UserMapper_ToUserDetailsDTO_Project_Domain_Users_User_
  name: ToUserDetailsDTO
  nameWithType: UserMapper.ToUserDetailsDTO
  fullName: Project.Application.Users.Mappers.UserMapper.ToUserDetailsDTO
- uid: Project.Domain.Users.User
  commentId: T:Project.Domain.Users.User
  parent: Project.Domain.Users
  href: Project.Domain.Users.User.html
  name: User
  nameWithType: User
  fullName: Project.Domain.Users.User
- uid: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  commentId: T:Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
  parent: Project.Application.Users.Queries.GetUserDetails
  href: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO.html
  name: UserDetailsDTO
  nameWithType: UserDetailsDTO
  fullName: Project.Application.Users.Queries.GetUserDetails.UserDetailsDTO
- uid: Project.Domain.Users
  commentId: N:Project.Domain.Users
  href: Project.html
  name: Project.Domain.Users
  nameWithType: Project.Domain.Users
  fullName: Project.Domain.Users
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Domain
    name: Domain
    href: Project.Domain.html
  - name: .
  - uid: Project.Domain.Users
    name: Users
    href: Project.Domain.Users.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Domain
    name: Domain
    href: Project.Domain.html
  - name: .
  - uid: Project.Domain.Users
    name: Users
    href: Project.Domain.Users.html
- uid: Project.Application.Users.Queries.GetUserDetails
  commentId: N:Project.Application.Users.Queries.GetUserDetails
  href: Project.html
  name: Project.Application.Users.Queries.GetUserDetails
  nameWithType: Project.Application.Users.Queries.GetUserDetails
  fullName: Project.Application.Users.Queries.GetUserDetails
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Queries
    name: Queries
    href: Project.Application.Users.Queries.html
  - name: .
  - uid: Project.Application.Users.Queries.GetUserDetails
    name: GetUserDetails
    href: Project.Application.Users.Queries.GetUserDetails.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Application
    name: Application
    href: Project.Application.html
  - name: .
  - uid: Project.Application.Users
    name: Users
    href: Project.Application.Users.html
  - name: .
  - uid: Project.Application.Users.Queries
    name: Queries
    href: Project.Application.Users.Queries.html
  - name: .
  - uid: Project.Application.Users.Queries.GetUserDetails
    name: GetUserDetails
    href: Project.Application.Users.Queries.GetUserDetails.html
