### YamlMime:ManagedReference
items:
- uid: Project.Tests.Unit.Application.UsersTests
  commentId: N:Project.Tests.Unit.Application.UsersTests
  id: Project.Tests.Unit.Application.UsersTests
  children:
  - Project.Tests.Unit.Application.UsersTests.GetUserDetailsQueryHandlerTests
  - Project.Tests.Unit.Application.UsersTests.RegisterUserCommandTests
  langs:
  - csharp
  - vb
  name: Project.Tests.Unit.Application.UsersTests
  nameWithType: Project.Tests.Unit.Application.UsersTests
  fullName: Project.Tests.Unit.Application.UsersTests
  type: Namespace
  assemblies:
  - Project.Tests.Unit
references:
- uid: Project.Tests.Unit.Application.UsersTests.GetUserDetailsQueryHandlerTests
  commentId: T:Project.Tests.Unit.Application.UsersTests.GetUserDetailsQueryHandlerTests
  href: Project.Tests.Unit.Application.UsersTests.GetUserDetailsQueryHandlerTests.html
  name: GetUserDetailsQueryHandlerTests
  nameWithType: GetUserDetailsQueryHandlerTests
  fullName: Project.Tests.Unit.Application.UsersTests.GetUserDetailsQueryHandlerTests
- uid: Project.Tests.Unit.Application.UsersTests.RegisterUserCommandTests
  commentId: T:Project.Tests.Unit.Application.UsersTests.RegisterUserCommandTests
  href: Project.Tests.Unit.Application.UsersTests.RegisterUserCommandTests.html
  name: RegisterUserCommandTests
  nameWithType: RegisterUserCommandTests
  fullName: Project.Tests.Unit.Application.UsersTests.RegisterUserCommandTests
