### YamlMime:ManagedReference
items:
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests
  commentId: T:Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests
  id: InternalCommandBaseTests
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  children:
  - Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
  - Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
  langs:
  - csharp
  - vb
  name: InternalCommandBaseTests
  nameWithType: InternalCommandBaseTests
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests
  type: Class
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: InternalCommandBaseTests
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
    startLine: 4
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  syntax:
    content: public class InternalCommandBaseTests
    content.vb: Public Class InternalCommandBaseTests
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
  commentId: M:Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
  id: Constructor_ShouldGenerateNewId_WhenNoIdProvided
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests
  langs:
  - csharp
  - vb
  name: Constructor_ShouldGenerateNewId_WhenNoIdProvided()
  nameWithType: InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided()
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided()
  type: Method
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Constructor_ShouldGenerateNewId_WhenNoIdProvided
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
    startLine: 13
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  syntax:
    content: >-
      [Fact]

      public void Constructor_ShouldGenerateNewId_WhenNoIdProvided()
    content.vb: >-
      <Fact>

      Public Sub Constructor_ShouldGenerateNewId_WhenNoIdProvided()
  overload: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided*
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
  commentId: M:Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
  id: Constructor_ShouldUseProvidedId_WhenIdProvided
  parent: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests
  langs:
  - csharp
  - vb
  name: Constructor_ShouldUseProvidedId_WhenIdProvided()
  nameWithType: InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided()
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided()
  type: Method
  source:
    remote:
      path: src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
      branch: main
      repo: https://github.com/Joaoaalves/dotnet-boilerplate.git
    id: Constructor_ShouldUseProvidedId_WhenIdProvided
    path: ../src/tests/Project.Tests.UnitTests/Application/ConfigurationTests/Commands/InternalCommandBaseTests.cs
    startLine: 23
  assemblies:
  - Project.Tests.UnitTests
  namespace: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  syntax:
    content: >-
      [Fact]

      public void Constructor_ShouldUseProvidedId_WhenIdProvided()
    content.vb: >-
      <Fact>

      Public Sub Constructor_ShouldUseProvidedId_WhenIdProvided()
  overload: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided*
  attributes:
  - type: Xunit.FactAttribute
    ctor: Xunit.FactAttribute.#ctor
    arguments: []
references:
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  commentId: N:Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  href: Project.html
  name: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  nameWithType: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
  spec.csharp:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Tests
    name: Tests
    href: Project.Tests.html
  - name: .
  - uid: Project.Tests.UnitTests
    name: UnitTests
    href: Project.Tests.UnitTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application
    name: Application
    href: Project.Tests.UnitTests.Application.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests
    name: ConfigurationTests
    href: Project.Tests.UnitTests.Application.ConfigurationTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
    name: Commands
    href: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.html
  spec.vb:
  - uid: Project
    name: Project
    href: Project.html
  - name: .
  - uid: Project.Tests
    name: Tests
    href: Project.Tests.html
  - name: .
  - uid: Project.Tests.UnitTests
    name: UnitTests
    href: Project.Tests.UnitTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application
    name: Application
    href: Project.Tests.UnitTests.Application.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests
    name: ConfigurationTests
    href: Project.Tests.UnitTests.Application.ConfigurationTests.html
  - name: .
  - uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands
    name: Commands
    href: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided*
  commentId: Overload:Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
  href: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.html#Project_Tests_UnitTests_Application_ConfigurationTests_Commands_InternalCommandBaseTests_Constructor_ShouldGenerateNewId_WhenNoIdProvided
  name: Constructor_ShouldGenerateNewId_WhenNoIdProvided
  nameWithType: InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldGenerateNewId_WhenNoIdProvided
- uid: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided*
  commentId: Overload:Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
  href: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.html#Project_Tests_UnitTests_Application_ConfigurationTests_Commands_InternalCommandBaseTests_Constructor_ShouldUseProvidedId_WhenIdProvided
  name: Constructor_ShouldUseProvidedId_WhenIdProvided
  nameWithType: InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
  fullName: Project.Tests.UnitTests.Application.ConfigurationTests.Commands.InternalCommandBaseTests.Constructor_ShouldUseProvidedId_WhenIdProvided
