### YamlMime:ManagedReference
items:
- uid: Project.Api.Configurations
  commentId: N:Project.Api.Configurations
  id: Project.Api.Configurations
  children:
  - Project.Api.Configurations.ConfigurationsModule
  - Project.Api.Configurations.CorsConfiguration
  - Project.Api.Configurations.ExecutionContextAccessor
  langs:
  - csharp
  - vb
  name: Project.Api.Configurations
  nameWithType: Project.Api.Configurations
  fullName: Project.Api.Configurations
  type: Namespace
  assemblies:
  - Project.Api
references:
- uid: Project.Api.Configurations.ConfigurationsModule
  commentId: T:Project.Api.Configurations.ConfigurationsModule
  href: Project.Api.Configurations.ConfigurationsModule.html
  name: ConfigurationsModule
  nameWithType: ConfigurationsModule
  fullName: Project.Api.Configurations.ConfigurationsModule
- uid: Project.Api.Configurations.CorsConfiguration
  commentId: T:Project.Api.Configurations.CorsConfiguration
  href: Project.Api.Configurations.CorsConfiguration.html
  name: CorsConfiguration
  nameWithType: CorsConfiguration
  fullName: Project.Api.Configurations.CorsConfiguration
- uid: Project.Api.Configurations.ExecutionContextAccessor
  commentId: T:Project.Api.Configurations.ExecutionContextAccessor
  href: Project.Api.Configurations.ExecutionContextAccessor.html
  name: ExecutionContextAccessor
  nameWithType: ExecutionContextAccessor
  fullName: Project.Api.Configurations.ExecutionContextAccessor
