### YamlMime:ManagedReference
items:
- uid: Project.Application.Configuration.Commands.Behaviors
  commentId: N:Project.Application.Configuration.Commands.Behaviors
  id: Project.Application.Configuration.Commands.Behaviors
  children:
  - Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior`2
  - Project.Application.Configuration.Commands.Behaviors.LoggingBehavior`2
  - Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior`2
  langs:
  - csharp
  - vb
  name: Project.Application.Configuration.Commands.Behaviors
  nameWithType: Project.Application.Configuration.Commands.Behaviors
  fullName: Project.Application.Configuration.Commands.Behaviors
  type: Namespace
  assemblies:
  - Project.Application
references:
- uid: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior`2
  commentId: T:Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior`2
  href: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior-2.html
  name: ICommandPipelineBehavior<TCommand, TResult>
  nameWithType: ICommandPipelineBehavior<TCommand, TResult>
  fullName: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior<TCommand, TResult>
  nameWithType.vb: ICommandPipelineBehavior(Of TCommand, TResult)
  fullName.vb: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior(Of TCommand, TResult)
  name.vb: ICommandPipelineBehavior(Of TCommand, TResult)
  spec.csharp:
  - uid: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior`2
    name: ICommandPipelineBehavior
    href: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior-2.html
  - name: <
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior`2
    name: ICommandPipelineBehavior
    href: Project.Application.Configuration.Commands.Behaviors.ICommandPipelineBehavior-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior`2
  commentId: T:Project.Application.Configuration.Commands.Behaviors.LoggingBehavior`2
  href: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior-2.html
  name: LoggingBehavior<TCommand, TResult>
  nameWithType: LoggingBehavior<TCommand, TResult>
  fullName: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior<TCommand, TResult>
  nameWithType.vb: LoggingBehavior(Of TCommand, TResult)
  fullName.vb: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior(Of TCommand, TResult)
  name.vb: LoggingBehavior(Of TCommand, TResult)
  spec.csharp:
  - uid: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior`2
    name: LoggingBehavior
    href: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior-2.html
  - name: <
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior`2
    name: LoggingBehavior
    href: Project.Application.Configuration.Commands.Behaviors.LoggingBehavior-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior`2
  commentId: T:Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior`2
  href: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior-2.html
  name: UserInjectionCommandBehavior<TCommand, TResult>
  nameWithType: UserInjectionCommandBehavior<TCommand, TResult>
  fullName: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior<TCommand, TResult>
  nameWithType.vb: UserInjectionCommandBehavior(Of TCommand, TResult)
  fullName.vb: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior(Of TCommand, TResult)
  name.vb: UserInjectionCommandBehavior(Of TCommand, TResult)
  spec.csharp:
  - uid: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior`2
    name: UserInjectionCommandBehavior
    href: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior-2.html
  - name: <
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior`2
    name: UserInjectionCommandBehavior
    href: Project.Application.Configuration.Commands.Behaviors.UserInjectionCommandBehavior-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: ','
  - name: " "
  - name: TResult
  - name: )
